encantos_mei/urls.py
from django.contrib import admin
from django.urls import include, path
from shop.views import IndexView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("shop/", include("shop.urls")),
    path("admin/", admin.site.urls),
    path('messages/', include('shop_messages.urls')),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import (
    IndexView,
    ProductListView,
    ProductDetailView,
    ServiceListView,
    ServiceDetailView,
    ContactView,
    ProductCreateView,
    ServiceCreateView,
    ProductSearchView,
    LoginView,
    LogoutView,
    RegisterView,
    ProfileView,
    EditProfileView,
    ProductDeleteView,
    AboutView,
    PagesListView,
    ProductEditView,
    ServiceDeleteView,
    ServiceEditView,
    ClientListView,
    ClientCreateView,
    ClientEditView,
    ClientDeleteView
)

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path('products/', ProductListView.as_view(), name='products'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('services/', ServiceListView.as_view(), name='services'),
    path('services/<int:pk>/', ServiceDetailView.as_view(), name='service_detail'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('create_product/', ProductCreateView.as_view(), name='create_product'),
    path('create_service/', ServiceCreateView.as_view(), name='create_service'),
    path('search/', ProductSearchView.as_view(), name='search_products'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('edit_profile/', EditProfileView.as_view(), name='edit_profile'),
    path('products/delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
    path('about/', AboutView.as_view(), name='about'),
    path('pages/', PagesListView.as_view(), name='pages'),
    path('edit_product/<int:pk>/', ProductEditView.as_view(), name='edit_product'),
    path('services/edit/<int:pk>/', ServiceEditView.as_view(), name='edit_service'),
    path('services/delete/<int:pk>/', ServiceDeleteView.as_view(), name='delete_service'),
    path('clients/', ClientListView.as_view(), name='clients'),
    path('clients/create/', ClientCreateView.as_view(), name='create_client'),
    path('clients/edit/<int:pk>/', ClientEditView.as_view(), name='edit_client'),
    path('clients/delete/<int:pk>/', ClientDeleteView.as_view(), name='delete_client'),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/models.py
from django.db import models
from django.contrib.auth.models import User

class Service(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.IntegerField()
    duration = models.PositiveIntegerField(help_text="Duración en minutos")
    image = models.ImageField(upload_to='services/', blank=True, null=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    price = models.IntegerField()
    image = models.ImageField(upload_to='products/', blank=True, null=True)
    brand = models.CharField(max_length=50, blank=True, null=True)
    stock = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=255, blank=True)
    phone_number = models.CharField(max_length=20, blank=True)
    profile_picture = models.ImageField(upload_to='profile_pictures/', blank=True, null=True)

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.views.generic import ListView, DetailView, CreateView
from django.urls import reverse_lazy
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from django.utils.decorators import method_decorator
from .models import Product, Service, Profile
from .forms import ProductForm, ServiceForm, SearchForm, CustomUserCreationForm, ProfileEditForm, ContactForm, ClientEditForm
from shop_messages.models import Message, Notification
from django.contrib.auth.models import User, Group

def is_admin(user):
    return user.groups.filter(name='Administradora de tienda').exists() or user.is_superuser

class IndexView(View):
    def get(self, request):
        products = Product.objects.all()
        services = Service.objects.all()
        
        is_admin_user = is_admin(request.user)

        return render(request, 'index.html', {
            'products': products,
            'services': services,
            'messages': messages.get_messages(request),
            'is_admin': is_admin_user,
        })

class ProductListView(ListView):
    model = Product
    template_name = 'products.html'
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context['is_admin'] = is_admin(user)
        return context
class ProductDetailView(DetailView):
    model = Product
    template_name = 'product_detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_admin'] = is_admin(self.request.user)
        product = self.object
        context['image_url'] = product.image.url if product.image else None
        context['stock'] = product.stock
        return context

@method_decorator(user_passes_test(is_admin), name='dispatch')
class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'create_product.html'
    success_url = reverse_lazy('products')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_admin'] = is_admin(self.request.user)
        return context

@method_decorator(user_passes_test(is_admin), name='dispatch')
class ProductEditView(View):
    def get(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        form = ProductForm(instance=product)
        return render(request, 'edit_product.html', {'form': form, 'product': product})

    def post(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        form = ProductForm(request.POST, request.FILES, instance=product)
        
        if form.is_valid():
            form.save()
            messages.success(request, "Producto actualizado con éxito.")
            return redirect('products')
        else:
            messages.error(request, "Error, formulario inválido.")
        
        return render(request, 'edit_product.html', {'form': form, 'product': product})

@method_decorator(user_passes_test(is_admin), name='dispatch')
class ProductDeleteView(View):
    def post(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        product.delete()
        messages.success(request, "Producto eliminado con éxito.")
        return redirect('products')

class ProductSearchView(View):
    def get(self, request):
        form = SearchForm()
        results = []
        search_form = SearchForm(request.GET)

        if search_form.is_valid():
            query = search_form.cleaned_data['query']
            results = Product.objects.filter(name__icontains=query)

        is_admin_user = is_admin(request.user)

        context = {'form': form, 'results': results, 'is_admin': is_admin_user,}

        return render(request, 'search_products.html', context)

class ServiceListView(ListView):
    model = Service
    template_name = 'services.html'
    context_object_name = 'services'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_admin'] = is_admin(self.request.user)
        return context

class ServiceDetailView(DetailView):
    model = Service
    template_name = 'service_detail.html'
    context_object_name = 'service'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_admin'] = is_admin(self.request.user)
        service = self.object
        context['image_url'] = service.image.url if service.image else None
        return context

@method_decorator(user_passes_test(is_admin), name='dispatch')
class ServiceCreateView(CreateView):
    model = Service
    form_class = ServiceForm
    template_name = 'create_service.html'
    success_url = reverse_lazy('services')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_admin'] = is_admin(self.request.user)
        return context

@method_decorator(user_passes_test(is_admin), name='dispatch')
class ServiceEditView(View):
    def get(self, request, pk):
        service = get_object_or_404(Service, pk=pk)
        form = ServiceForm(instance=service)
        return render(request, 'edit_service.html', {'form': form, 'service': service})

    def post(self, request, pk):
        service = get_object_or_404(Service, pk=pk)
        form = ServiceForm(request.POST, request.FILES, instance=service)
        print("Valor de price enviado:", request.POST.get('price'))
        
        if form.is_valid():
            form.save()
            messages.success(request, "Servicio actualizado con éxito.")
            return redirect('services')
        else:
            messages.error(request, "Error, formulario inválido.")
            print(form.errors)
        
        return render(request, 'edit_service.html', {'form': form, 'service': service})

@method_decorator(user_passes_test(is_admin), name='dispatch')
class ServiceDeleteView(View):
    def post(self, request, pk):
        service = get_object_or_404(Service, pk=pk)
        service.delete()
        messages.success(request, "Servicio eliminado con éxito.")
        return redirect('services')

class LoginView(View):
    def get(self, request):
        form = AuthenticationForm()
        return render(request, 'login.html', {'form': form})

    def post(self, request):
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f"Bienvenido {username}!")
                return redirect('index')
            else:
                messages.error(request, "Error, datos incorrectos.")
        else:
            messages.error(request, "Error, formulario incorrecto.")

        return render(request, 'login.html', {'form': form})

class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('index')

class RegisterView(View):
    def get(self, request):
        form = CustomUserCreationForm()
        return render(request, 'register.html', {'form': form})

    def post(self, request):
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.email = form.cleaned_data['email']
            user.save()

            Profile.objects.create(
                user=user,
                address=form.cleaned_data['address'],
                phone_number=form.cleaned_data['phone_number']
            )
            username = form.cleaned_data.get('username')
            messages.success(request, f"¡Cuenta creada para {username}!")

            return redirect('login')
        else:
            messages.error(request, "Error, formulario inválido.")
        
        return render(request, 'register.html', {'form': form})

class ProfileView(View):
    def get(self, request):
        profile = get_object_or_404(Profile, user=request.user)
        return render(request, 'profile.html', {
            'profile': profile,
            'is_admin': is_admin(request.user),
        })
        
class EditProfileView(View):
    def get(self, request):
        profile = get_object_or_404(Profile, user=request.user)
        form = ProfileEditForm(instance=profile, user=request.user)
        return render(request, 'edit_profile.html', {
            'form': form,
            'profile': profile,
            'is_admin': is_admin(request.user),
        })

    def post(self, request):
        profile = get_object_or_404(Profile, user=request.user)
        form = ProfileEditForm(request.POST, request.FILES, instance=profile, user=request.user)

        if form.is_valid():
            request.user.email = form.cleaned_data['email']
            request.user.save()
            form.save()
            messages.success(request, "Perfil actualizado con éxito.")
            return redirect('profile')
        else:
            messages.error(request, "Error, formulario inválido.")
        
        return render(request, 'edit_profile.html', {
            'form': form,
            'profile': profile,
            'is_admin': is_admin(request.user),
        })

class ContactView(View):
    def get(self, request):
        form = ContactForm()
        return render(request, 'contact.html', {'form': form})

    def post(self, request):
        form = ContactForm(request.POST)
        if form.is_valid():
            admin_users = User.objects.filter(groups__name='Administradora de tienda')

shop/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% block title %}
                Encantos Mei
            {% endblock %}
        </title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link rel="icon" href="{% static 'images/icon.svg' %}" type="image/svg+xml">
    </head>

    <body>
        <nav class="navbar navbar-expand-lg custom-navbar" role="navigation">
    <div class="container-fluid">
        <a class="navbar-brand {% if request.path == '/shop/' or request.path == '/index/' %}active{% endif %}" href="{% url 'index' %}">
            <img src="{% static 'images/logo.svg' %}" alt="Logo de Encantos Mei" class="d-inline-block align-text-top" width="30" height="30"> 
            Inicio | Encantos Mei
        </a>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/shop/products/' %}active{% endif %}" href="{% url 'products' %}">Productos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/shop/services/' %}active{% endif %}" href="{% url 'services' %}">Servicios</a>
                </li>

                        {% if user.is_authenticated %}

                        {% if is_admin %}
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == '/shop/clients/' %}active{% endif %}" href="{% url 'clients' %}">Clientes</a>
                        </li>
                    {% endif %}

                            <li class="nav-item">
                                <span class="navbar-text d-flex align-items-center" style="white-space: nowrap;">
                                    {% if profile and profile.profile_picture %}
                                        <img src="{{ profile.profile_picture.url }}" alt="Imagen de perfil" width="30" height="30" class="rounded-circle me-2" style="margin-right: 5px;">
                                    {% endif %}{{ user.username }}
                                </span>
                            </li>
                    
                            <li class="nav-item">
                                <a class="nav-link {% if request.path == '/shop/profile/' %}active{% endif %}" href="{% url 'profile' %}">
                                    Mi perfil
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% if request.path == '/messages/messages/' %}active{% endif %}" href="{% url 'messages' %}">
                                    Mensajes
                                    
                                    {% if notification_count %}
                                        <span class="badge bg-danger">
                                            {{ notification_count }}
                                        </span>
                                    {% endif %}
                                    
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% if request.path == '/shop/logout/' %}active{% endif %}" href="{% url 'logout' %}">
                                    Cerrar Sesión
                                </a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link {% if request.path == '/shop/login/' %}active{% endif %}" href="{% url 'login' %}">
                                    Iniciar Sesión
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% if request.path == '/shop/register/' %}active{% endif %}" href="{% url 'register' %}">
                                    Registrar
                                </a>
                            </li>

                        {% endif %}

                    </ul>
                    
                    <div style="display: flex; justify-content: center; align-items: center; margin: 20px auto; max-width: 400px; height: 80px;">
                        <form class="form-search" method="GET" action="{% url 'search_products' %}" role="search" style="display: flex; width: 100%; align-items: center;">
                            <input  type="search" name="query" placeholder="Buscar productos" aria-label="Search" style="flex: 1; margin-right: 10px; border: 1px solid #ddd; border-radius: 5px; padding: 10px;">
                            <button class="btn btn-outline-light" type="submit" style="border: 1px solid #ddd; border-radius: 5px; padding: 10px 20px;">
                                Buscar
                            </button>
                        </form>
                    </div>
                
                </div>
            </div>
        </nav>

        <div class="content">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="bg-light text-center text-lg-start mt-auto">
            <div class="container p-2">
                <div class="row justify-content-between align-items-center">
                    <div class="col-auto">
                        <h5 style="display: inline;">Encantos Mei | © 2024 Todos los derechos reservados</p>
                    </div>
                    <div class="col-auto">
                        <ul class="list-unstyled d-flex" style="font-size: 0.8rem; padding: 0; margin: 0;">
                            <li class="me-3"><a href="{% url 'contact' %}" class="text-dark text-decoration-none hover-link">Contacto</a></li>
                            <li class="me-3"><a href="{% url 'about' %}" class="text-dark text-decoration-none hover-link">Acerca de</a></li>
                            <li><a href="{% url 'pages' %}" class="text-dark text-decoration-none hover-link">Mapa del sitio</a></li>
                        </ul>
                    </div>
                    <div class="col-auto">
                        <h5 style="display: inline;">Síguenos |</h5>
                        <a href="#" class="me-2 text-dark hover-link" style="display: inline;"><i class="bi bi-facebook" style="font-size: 1.2rem;"></i></a>
                        <a href="#" class="text-dark hover-link" style="display: inline;"><i class="bi bi-instagram" style="font-size: 1.2rem;"></i></a>
                    </div>
                </div>
            </div>
        </footer>
        

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+Knujsl5/12h0a5y/jH5LOJ3Z7t85o0L09y/jR+3Z1E6Q6Z" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    </body>
</html>

shop/templates/clients.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Encantos Mei | Clientes
{% endblock %}

{% block content %}
    <h1 class="text-center my-4">Nuestros Clientes</h1>

    {% if message %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endif %}
    
    {% if user.is_authenticated %}
        {% if is_admin %}
            <a href="{% url 'create_client' %}" class="btn btn-primary mb-3">
                Agregar Cliente
            </a>
        {% endif %}
    {% endif %}

    <div class="container">
        <table class="table table-bordered">
            <thead class="thead-light">
                <tr>
                    <th>Nombre de Usuario</th>
                    <th>Email</th>
                    <th>Teléfono</th>
                    <th>Dirección</th>
                    {% if is_admin %}
                    <th>Acciones</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for client in clients %}
                    <tr>
                        <td>{{ client.user.username }}</td>
                        <td>{{ client.user.email }}</td>
                        <td>{{ client.phone_number }}</td>
                        <td>{{ client.address }}</td>
                        {% if is_admin %}
                        <td>
                            <a href="{% url 'edit_client' client.pk %}" class="btn btn-warning btn-sm">
                                Editar
                            </a>
                            <form method="POST" action="{% url 'delete_client' client.pk %}" style="display: inline;">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('¿Estás segura de que deseas eliminar este cliente?');">
                                    Eliminar
                                </button>
                            </form>
                        </td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div style="height: 50px;"></div>
{% endblock %}

shop/templates/contact.html
{% extends 'base.html' %}

{% block title %}
    Encantos Mei - Contacto
{% endblock %}

{% block content %}
    <h1 class="text-center my-4">
        Contacto
    </h1>
    <div class="container" style="display: flex; flex-direction: column;">
    
        <div class="alert alert-success" style="display: none;" id="alert-message">

        {% if message %}
            <script>
                document.addEventListener("DOMContentLoaded", function() {
                    const alertDiv = document.getElementById('alert-message');
                    alertDiv.innerHTML = "{{ message }}";
                    alertDiv.style.display = 'block';
                });
            </script>
        {% endif %}

        </div>
        <form method="post">
            {% csrf_token %}
            {% if not user.is_authenticated %}
                {{ form.name.label }} {{ form.name }}
            {% endif %}
            {{ form.email.label }} {{ form.email }}
            {{ form.message.label }} {{ form.message }}
            <button type="submit" class="btn btn-primary">Enviar</button>
        </form>
    </div>

{% endblock %}

shop/templates/create_client.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Encantos Mei | Crear Cliente
{% endblock %}

{% block content %}
    <h1 class="text-center" style="margin-top: 50px; margin-bottom: 50px;">
        Crear Cliente
    </h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                </label>
                <input type="{{ field.field.widget.input_type }}" id="{{ field.id_for_label }}" name="{{ field.name }}" class="form-control" required="{{ field.field.required }}" value="{{ field.value|default_if_none:'' }}">
                {% if field.help_text %}
                    <small class="form-text text-muted">
                        {{ field.help_text }}
                    </small>
                {% endif %}
            </div>
        {% endfor %}
        <div class="form-group">
            <button type="submit" class="btn btn-primary">
                Crear Cliente
            </button>
        </div>
    </form>
    
    <p class="text-center">
        <a href="{% url 'clients' %}" class="btn btn-secondary">Cancelar</a>
    </p>
{% endblock %}

shop/templates/edit_product.html
{% extends 'base.html' %}

{% block title %}
    Editar Producto - Encantos Mei
{% endblock %}

{% block content %}
    <h1 style="margin-top: 50px; margin-bottom: 50px;">
        Editar Producto: {{ product.name }}
    </h1>
    <form method="POST" action="{% url 'edit_product' product.pk %}" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="id_name">Nombre del Producto:</label>
            <input type="text" id="id_name" name="name" value="{{ form.name.value }}" required>
        </div>
    
        <div class="form-group">
            <label for="id_brand">Marca:</label>
            <input type="text" id="id_brand" name="brand" value="{{ form.brand.value }}" required>
        </div>
    
        <div class="form-group">
            <label for="id_description">Descripción:</label>
            <textarea id="id_description" name="description" required>{{ form.description.value }}</textarea>
        </div>
    
        <div class="form-group">
            <label for="id_price">Precio:</label>
            <input type="text" id="id_price" name="price" value="{{ form.price.value }}" required>
        </div>
    
        <div class="form-group">
            <label for="id_stock">Cantidad en stock:</label>
            <input type="number" id="id_stock" name="stock" value="{{ form.stock.value }}" required>
        </div>
    
        <div class="form-group">
            <label for="id_image">Imagen:</label>
            Actualmente: <a href="{{ product.image.url }}">{{ product.image.url }}</a><br>
            <input type="checkbox" name="image-clear" id="image-clear_id">
            <label for="image-clear_id">Eliminar imagen actual</label><br>
            Modificar: <input type="file" name="image" accept="image/*" id="id_image">
        </div>
    
        <div class="form-group">
            <input type="submit" value="Actualizar Producto">
        </div>
    </form>
    
    <a href="{% url 'products' %}" class="btn">
        Volver a Productos
    </a>
{% endblock %}

shop/templates/edit_service.html
{% extends 'base.html' %}

{% block title %}
    Editar Servicio - Encantos Mei
{% endblock %}

{% block content %}
    <h1 style="margin-top: 50px; margin-bottom: 50px;">
        Editar Servicio: {{ service.name }}
    </h1>
    <form method="POST" action="{% url 'edit_service' service.pk %}" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group">
            <label for="id_name">Nombre del Servicio:</label>
            <input type="text" id="id_name" name="name" value="{{ form.name.value }}" required>
        </div>

        <div class="form-group">
            <label for="id_description">Descripción:</label>
            <textarea id="id_description" name="description" required>{{ form.description.value }}</textarea>
        </div>

        <div class="form-group">
            <label for="id_price">Precio:</label>
            <input type="text" id="id_price" name="price" value="{{ form.price.value|default:service.price }}" required>
        </div>

        <div class="form-group">
            <label for="id_duration">Duración (minutos):</label>
            <input type="text" id="id_duration" name="duration" value="{{ form.duration.value }}" required>
        </div>

        <div class="form-group">
            <label for="id_image">Imagen:</label>
            {% if service.image %}
                Actualmente: 
                <a href="{{ service.image.url }}">{{ service.image.url }}</a><br>
                <input type="checkbox" name="image-clear" id="image-clear_id">
                <label for="image-clear_id">Eliminar imagen actual</label><br>
            {% endif %}
            Modificar: <input type="file" name="image" accept="image/*" id="id_image">
        </div>

        <div class="form-group">
            <input type="submit" value="Actualizar Servicio">
        </div>
    </form>

    <a href="{% url 'services' %}" class="btn">Volver a Servicios</a>
{% endblock %}

shop/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Encantos Mei
{% endblock %}

{% block content %}

<h1 class="text-center" style="margin-bottom: 100px; margin-top: 80px;">Bienvenida a Encantos Mei</h1>

    <div class="container my-4" style="display: flex; flex-direction: column;">
        <h2 class="text-center" style="margin-bottom: 80px;">Servicios Destacados</h2>
        
        <div class="row">
            <div class="col-md-4">
                <h3>Manicura</h3>
                <p>Disfruta de nuestras manicuras clásicas y diseños personalizados.</p>
            </div>
            <div class="col-md-4">
                <h3>Diseños de uñas</h3>
                <p>Haz que tus uñas sean una obra de arte con nuestros diseños únicos.</p>
            </div>
            <div class="col-md-4">
                <h3>Colocación de pestañas</h3>
                <p>Todas las técnicas para que te veas maravillosa.</p>
            </div>
        </div>
    </div>

{% endblock %}